### ISSUE TITLE
vcpkg  error

### ISSUE THREAD

**Issue by taurynamonsterxdd** [Gn3po4g/OrbWalker#100]
vcpkg : The term 'vcpkg' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ vcpkg install imgui[core,dx11-binding,win32-binding]:x64-windows-stat ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (vcpkg:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Noroby** [comment]
just click the link of vcpkg in README and install it.
it's easy to do.
