### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by M5TTH** [Gn3po4g/OrbWalker#126]
i tested in pratice tool and crashed

**Comment by M5TTH** [comment]
yes new file

**Comment by 2b2tplayer** [comment]
it was working but now I crash too when I try to join a game (pratice or any mode)

**Comment by Gn3po4g** [comment]
I fixed an incorrect offset, not sure if that solved the problem.

**Comment by 2b2tplayer** [comment]
Just built it, it works, Can't upload the Hid.dll but if @M5TTH knows how to build it themselves it's okay

**Comment by xunyangjian1** [comment]
May I ask what shortcut key I need to start it

**Comment by 2b2tplayer** [comment]
the gui should be enabled by default (unless you are using my fork) chances are if you are using the latest release in the main fork it wont work, but key is Insert
