### ISSUE TITLE
error when starting the game with the dll in the game folder

### ISSUE THREAD

**Issue by Estagiariodorh** [Gn3po4g/OrbWalker#127]
The same recent dll for download was working just now, but the game had a small update, and after that it started to crash, in normal game, training mode, if I rename the dll, nothing happens, but if I leave HID or Hid or even hid, it hangs, how to solve it?

**Comment by 2b2tplayer** [comment]
for now you can use the release in my fork, code is exactly the same

**Comment by Estagiariodorh** [comment]
but it's the one I'm using. I played about 3.4 games, and after the "update" I have been getting the error of the game crashing

**Comment by Estagiariodorh** [comment]
https://github.com/Gn3po4g/OrbWalker/releases/tag/14.8

I'm using the dll available for download at this link

**Comment by 2b2tplayer** [comment]
Are you sure you are using the release on my fork? I've been using it all day and had no crash, weird

**Comment by 2b2tplayer** [comment]
use this one https://github.com/2b2tplayer/Orb/releases/tag/release and tell me if it still crashes

**Comment by Estagiariodorh** [comment]
OK, I'll test it and let you know

**Comment by Estagiariodorh** [comment]
the game continues to crash, even using a dll that you made available, I'm on the br server... the strange thing is that just now it was working fine, before the update.

**Comment by 2b2tplayer** [comment]
then it mught be an offsets issue, unfortunately I don't have the patterns nor the knowledge to find those myself (I'm new to this) so I can't help you

**Comment by Estagiariodorh** [comment]
continues to close regardless of Hid.dll, game version 14.8.575.9209. I checked the offsets to see if anything had changed, but apparently it remains the same. I don't know how to solve it.
I'm sorry for wanting quick answers, but I liked the way it was working, and then out of nowhere it stopped working.

**Comment by Estagiariodorh** [comment]
No need to worry, thank you for responding. later in detail, I'll check them one by one, wait to see if people make them available for comparison, I'm using these ones here to compare : 

https://www.unknowncheats.me/forum/league-of-legends/310587-league-legends-reversal-structs-offsets-596.html

**Comment by 2b2tplayer** [comment]
those might not be the latest ones. Since you said it had a small update
then the only way of checking them is by having the patterns and dumping
them yourself from the newest patch. I do not have all of the patterns
otherwise I would've updated it

**Comment by Estagiariodorh** [comment]
I understand, still. Thank you for at least clarifying and trying to help :D

**Comment by KountriOTB** [comment]
i solved this, i went to toirscript website (an script service i used to use) and downloaded a file called #league of legends hotfix" yesterday riot launched a small update but if you replace the files league of legends.exe and stumb.dll the game runs in a older client version and the game does not crashes, here is the link https://drive.google.com/file/d/1TqoftYKxms3bBtKjdmU11bahuRcZb1Zr/view

**Comment by KountriOTB** [comment]
pass is 123 xd

**Comment by Estagiariodorh** [comment]
> passe é 123 xd

Thank you very much, I used the hotfix and it worked great. <3

**Comment by Gn3po4g** [comment]
Late update, sorry.

**Comment by 2b2tplayer** [comment]
would you mind sharing the patterns?

**Comment by Gn3po4g** [comment]
{"oPingNet",          "48 8B F9 48 8B 05 ? ? ? ? 48 89 74 24 ?",                             6},
  {"oGameState",        "48 8B 05 ? ? ? ? 4C 8B FA 83 78 0C 02",                               3},
  {"oGameTime",         "F3 0F 5C 35 ? ? ? ? 0F 28 F8",                                        4},
  {"oLocalPlayer",      "74 6A 48 8B 0D ? ? ? ? 48 8D 54 24 ?",                                5},
  {"oObjUnderMouse",    "48 8B 05 ? ? ? ? 48 8B F9 33 C9 48 8B DA",                            3},
  {"oMouseScreenPos",   "48 8B 0D ? ? ? ? 4C 8D 45 67",                                        3},
  {"oHeroList",         "48 8B 05 ? ? ? ? 45 33 E4 0F 57 C0",                                  3},
  {"oMinionList",       "73 0C 48 8B 05 ? ? ? ? F3 0F 10 40 ?",                                5},
  {"oTurretList",       "48 8B 1D ? ? ? ? 48 8B 5B 28",                                        3},
  {"oInhibList",        "4C 8B 05 ? ? ? ? 49 8B 78 08 41 8B 40 10 48 8D 0C C7 48 3B F9 73 3E", 3},
  {"oChatClient",       "41 FF D1 48 8B 0D ? ? ? ? 0F B6 D8",                                  6},
  {"oHudInstance",      "48 8B 0D ? ? ? ? 8B 57 10",                                           3},
  {"oViewProjMatrix",   "48 8D 0D ? ? ? ? 0F 10 00",                                           3},

  {"oGetPing",          "48 83 EC 28 0F B6 81 ? ? ? ? 4C 8B C1",                               0},
  {"oPrintChat",        "E8 ? ? ? ? 4C 8B C3 B2 01",                                           1},
  {"oIssueOrder",       "E8 ? ? ? ? 48 83 C4 48 C3 CC CC CC CC CC CC 48 83 EC 48",             1},
  {"oIssueMove",        "48 89 5C 24 ? 48 89 74 24 ? 57 48 81 EC ? ? ? ? 48 8B F1 41",         0},
  {"oAttackDelay",      "E8 ? ? ? ? 33 C0 F3 0F 11 83 ? ? ? ?",                                1},
  {"oTargetableToTeam", "40 53 48 83 EC 20 48 8B D9 E8 ? ? ? ? 84 C0 74 41",                   0},
  {"oMaterialRegistry", "E8 ? ? ? ? 8B 57 44",                                                 1}

**Comment by 2b2tplayer** [comment]
thank you
