### ISSUE TITLE
Questions about spellCast

### ISSUE THREAD

**Issue by LeonardoFBR** [Gn3po4g/OrbWalker#47]
Sorry for asking, I have a few questions.
1. It is not necessary to pass the indexes?
  // set spell position
  //targetInfo->SetCasterHandle(self->index());
  //targetInfo->SetTargetHandle(target->index());

2. The function does not have anticheat checks?

**Comment by Noroby** [comment]
I'm not sure, but you can cast spell without these two parameters.
