### ISSUE TITLE
Example of How To Get Buff Count

### ISSUE THREAD

**Issue by KetamineDev** [Gn3po4g/OrbWalker#71]
Hey Noroby, spoke to you a couple times before, I was using trying to make a twitch script with it, and I got it pretty much done, it took me a bit to figure out how to get buff_count for his passive, but the has_buffs method you have I don't even use,

`int get_venom_stacks(Object* target) const {
		const auto& buffs = target->buffs();
		for (const auto& buff : buffs) if (buff->name() == "TwitchDeadlyVenom") return buff->count();
		return 0;
	}`

**Comment by KetamineDev** [comment]
OH ALSO, your Buff_Count Offset (Ox38) is for Buff_Count_Alt, which when I tried using just returned "1" no matter the "Count" so I used (0x8C) for Buff_Count, and it worked as intended. (13.20 offsets)

**Comment by vacnex** [comment]
```C
constexpr inline uintptr_t BuffEntryBuffCount = 0x8C;
constexpr inline uintptr_t BuffEntryBuffCountAlt = 0x38; 
```

**Comment by Noroby** [comment]
ty. I'll change it.

**Comment by jinxx0** [comment]
> OH ALSO, your Buff_Count Offset (Ox38) is for Buff_Count_Alt, which when I tried using just returned "1" no matter the "Count" so I used (0x8C) for Buff_Count, and it worked as intended. (13.20 offsets)

Can u give me your discord?

**Comment by Noroby** [comment]
> > OH ALSO, your Buff_Count Offset (Ox38) is for Buff_Count_Alt, which when I tried using just returned "1" no matter the "Count" so I used (0x8C) for Buff_Count, and it worked as intended. (13.20 offsets)
> 
> Can u give me your discord?

Noroby#1428
