### ISSUE TITLE
crash when trying to get buff count

### ISSUE THREAD

**Issue by 1nteg3r** [Gn3po4g/OrbWalker#79]
`int Buff::count() { return MEMBER<int>(0x8C); }`

The count offset is correct

```
 auto me = Object::self();
 auto qSpell = me->GetSpell(SpellSlot_Q);
 auto eSpell = me->GetSpell(SpellSlot_E);
 int eLevel = eSpell->level();
 auto eTarget = get_skill_target(1200.0f);
 
 

 if (eTarget && game_time >= eSpell->readyTime() && me->mana() >= 90 && eTarget->compare_type_flags(Hero))
 {
     int stacks = 0;
     const auto& buffs = eTarget->buffs();
     for (const auto& buff : buffs) {
         if (buff->name() == "TwitchDeadlyVenom") {
             stacks += buff->count();
         }
     }
     
     float damage = (me->atkDmg() + (15 + (5 * eLevel)) * stacks) * (1 + (stacks* 0.25));
     if (eTarget->health() < damage)
     {
         PressKey2('E');
     }
 }
```
 
 it doesnt crash untill the target gets hit, therefore the script finds the buff, starts the count and it crashes, what can be the issue?

**Comment by jinxx0** [comment]
@1nteg3r can u give me your discord?

**Comment by jinxx0** [comment]
I need pattern for  GameTime = 0x21FA3A8, like this F3 0F 5C 35 ? ? ? ? 0F 28 F8

**Comment by Noroby** [comment]
You need to determine if the buff is valid, before using it.
 buff->is_valid() && game_time >= buff->starttime() && game_time <= buff->endtime() && buff->name() == name;

**Comment by 1nteg3r** [comment]
hey noroby one more thing while I test out if the buff issue is fixed.. yesterday i tried reading spellslot names but its not going well since i cant seem to decrypt the name using riotstring since the spelldata name is a char*
`std::string Spell::name(){ return *(char**)(Read<uintptr_t>(this) + 0x80); }`
this is how i try to read the name
`auto me = Object::self();
auto summoner1 = me->GetSpell(SpellSlot_Summoner1);
ImGui::Text(summoner1->name().data());`
this returns an encrypted string in my imgui window
