### ISSUE TITLE
I found all the skills that can reset basic attack.

### ISSUE THREAD

**Issue by liouyuwei** [Gn3po4g/OrbWalker#96]
I found all the skills that can reset basic attack. If there are any omissions or errors, please correct them. Sorry for my Chinese comments

![1](https://github.com/Noroby/OrbWalker/assets/97725942/bf41e159-ce1c-465b-bb0d-e50990040600)

https://github.com/Noroby/OrbWalker/blob/cca34f641d4336873d978b8f38b07fa1beeefd12/OrbWalker/class/Spell.cpp#L34-L37

https://github.com/liouyuwei/1/blob/d03caabf4d8b21f7e6733379a408be768a90a066/Spell.cpp#L35-L47

**Comment by vacnex** [comment]
Great!

**Comment by Noroby** [comment]
牛的
